(function () {
  const $ = (selector) => document.querySelector(selector);
  const page = document.body.dataset.page;
  document.querySelectorAll('.year').forEach((node) => { node.textContent = new Date().getFullYear(); });

  const gate = $('#age-gate');
  if (gate) {
    const confirmed = localStorage.getItem('imagepornAgeConfirmed') === 'yes';
    if (confirmed) gate.remove();
    $('#age-yes')?.addEventListener('click', () => { document.cookie = 'imagepornAgeConfirmed=yes; max-age=31536000; path=/; SameSite=Lax'; localStorage.setItem('imagepornAgeConfirmed', 'yes'); gate.remove(); });
    $('#age-no')?.addEventListener('click', () => { window.location.replace('https://www.google.com'); });
  }

  const configured = window.FIREBASE_CONFIG && !window.FIREBASE_CONFIG.apiKey.startsWith('YOUR_');
  if (configured && !firebase.apps.length) firebase.initializeApp(window.FIREBASE_CONFIG);
  const auth = configured && window.firebase?.auth ? firebase.auth() : null;
  const db = configured && window.firebase?.firestore ? firebase.firestore() : null;
  const setMessage = (text, success) => { const node = $('#auth-message') || $('#form-message'); if (node) { node.textContent = text; node.className = 'message' + (success ? ' success' : ''); } };
  const cleanError = (error) => { const text = error?.message || 'Something went wrong.'; const message = text.replace(/^Firebase:\s*/, '').replace(/\s*\([^)]*\)\.?$/, ''); return error?.code ? `${message} [${error.code}]` : message; };
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
  const hash = (value) => { let result = 0; for (let index = 0; index < value.length; index += 1) result = ((result << 5) - result) + value.charCodeAt(index) | 0; return Math.abs(result); };
  const imageName = () => 'imageporn-escorts-' + Math.random().toString(36).slice(2, 12);
  const uploadImage = async (file) => { if (!window.IMGBB_API_KEY || window.IMGBB_API_KEY.startsWith('YOUR_')) throw new Error('Add your ImgBB API key in firebase-config.js.'); const body = new FormData(); body.append('image', file); body.append('name', imageName()); const response = await fetch(`https://api.imgbb.com/1/upload?key=${encodeURIComponent(window.IMGBB_API_KEY)}`, { method: 'POST', body }); const result = await response.json(); if (!result.success) throw new Error(result.error?.message || 'Image upload failed.'); return result.data.url; };

  function authPage() {
    const form = $('#signup-form'); if (!form) return;
    if (!auth || !db) { setMessage('Firebase is not configured. Add the Firebase values in firebase-config.js.'); $('#auth-submit').disabled = true; return; }
    const signupMode = document.body.dataset.authMode === 'signup';
    $('#auth-submit').textContent = signupMode ? 'Create account' : 'Log in';
    auth.onAuthStateChanged(async (existingUser) => {
      if (!existingUser) return;
      try {
        await existingUser.reload();
        if (auth.currentUser?.emailVerified && new URLSearchParams(window.location.search).get('verified') !== '1') window.location.replace('dashboard.html');
      } catch (error) { setMessage(cleanError(error)); }
    });
    if (signupMode && new URLSearchParams(window.location.search).get('verified') === '1') {
      auth.onAuthStateChanged(async (verifiedUser) => {
        if (!verifiedUser) return setMessage('Email verified. Log in to continue.', true);
        try { await verifiedUser.reload(); if (auth.currentUser.emailVerified) window.location.replace('dashboard.html'); else setMessage('Your email is not verified yet. Open the Firebase verification link first.'); } catch (error) { setMessage(cleanError(error)); }
      });
    }
    const calculateAge = (value) => { if (!value) return null; const birthDate = new Date(`${value}T00:00:00`); const today = new Date(); let calculated = today.getFullYear() - birthDate.getFullYear(); const beforeBirthday = today.getMonth() < birthDate.getMonth() || (today.getMonth() === birthDate.getMonth() && today.getDate() < birthDate.getDate()); if (beforeBirthday) calculated -= 1; return calculated; };
    if (signupMode && $('#birthDate')) { const today = new Date(); const latestBirthDate = new Date(today.getFullYear() - 18, today.getMonth(), today.getDate()); const localDateValue = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; $('#birthDate').max = localDateValue(latestBirthDate); $('#birthDate').addEventListener('change', () => { const calculated = calculateAge($('#birthDate').value); $('#age').value = calculated ?? ''; $('#age-hint').textContent = calculated === null ? 'Select your date of birth.' : calculated < 18 ? 'You must be at least 18 years old.' : `${calculated} years old`; }); }
    $('#resend')?.addEventListener('click', async () => { if (!auth.currentUser) return setMessage('Log in first to resend the verification email.'); try { const settings = signupMode ? { url: `${window.location.origin}/signup.html?verified=1`, handleCodeInApp: false } : undefined; await auth.currentUser.sendEmailVerification(settings); setMessage('A new verification email has been sent.', true); } catch (error) { setMessage(cleanError(error)); } });
    form.addEventListener('submit', async (event) => { event.preventDefault(); const username = $('#username').value.trim(); const password = $('#password').value; try {
      if (!/^[A-Za-z0-9]+$/.test(username)) throw new Error('Username must contain only letters and numbers.');
      if (signupMode) {
        const birthDate = $('#birthDate').value; const age = calculateAge(birthDate); if (!birthDate || !Number.isInteger(age) || age < 18) throw new Error('Select a valid date of birth. You must be at least 18 years old.');
        const usernameRef = db.collection('usernames').doc(username.toLowerCase()); if ((await usernameRef.get()).exists) throw new Error('That username is already in use.');
        const credential = await auth.createUserWithEmailAndPassword($('#email').value.trim(), password);
        await usernameRef.set({ username, email: credential.user.email, uid: credential.user.uid });
        await db.collection('profiles').doc(username).set({ username, email: credential.user.email, uid: credential.user.uid, birthDate, age, gender: $('#gender').value, active: false, activated: false, visits: 0, createdAt: firebase.firestore.FieldValue.serverTimestamp() });
        const verificationSettings = { url: `${window.location.origin}/signup.html?verified=1`, handleCodeInApp: false }; await credential.user.sendEmailVerification(verificationSettings); $('#resend').classList.remove('hidden'); setMessage('Account created. Check your email and click the Firebase verification link. You will be redirected to your dashboard after verification.', true);
      } else {
        const usernameDoc = await db.collection('usernames').doc(username.toLowerCase()).get(); if (!usernameDoc.exists) throw new Error('Username or password is incorrect.');
        const credential = await auth.signInWithEmailAndPassword(usernameDoc.data().email, password);
        if (!credential.user.emailVerified) { $('#resend').classList.remove('hidden'); setMessage('Verify your email using the Firebase link before continuing.'); await auth.signOut(); return; }
        window.location.href = 'dashboard.html';
      }
    } catch (error) { setMessage(cleanError(error)); } });
  }

  function regionOptions(country, selected) { const regions = { Uganda: ['Central', 'Eastern', 'Northern', 'Western'], Kenya: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'], Tanzania: ['Arusha', 'Dar es Salaam', 'Dodoma', 'Mwanza'], Rwanda: ['Kigali', 'Eastern', 'Northern', 'Southern', 'Western'] }; const values = regions[country] || ['Central region', 'North region', 'South region']; return '<option value="">Choose region...</option>' + values.map((region) => `<option ${region === selected ? 'selected' : ''}>${region}</option>`).join(''); }
  function setupDropzone(zone, input, preview, multiple) { if (!zone || !input) return; const showFiles = (files) => { const selected = Array.from(files); if (!selected.length) return; if (selected.some((file) => !file.type.startsWith('image/') || file.size > 32 * 1024 * 1024)) return setMessage('Images must be image files below 32 MB each.'); input._files = multiple ? selected : [selected[0]]; if (preview) { preview.innerHTML = ''; input._files.forEach((file) => { const image = document.createElement('img'); image.src = URL.createObjectURL(file); preview.appendChild(image); }); } }; zone.addEventListener('click', () => input.click()); input.addEventListener('change', () => showFiles(input.files)); zone.addEventListener('dragover', (event) => { event.preventDefault(); zone.classList.add('drag'); }); zone.addEventListener('dragleave', () => zone.classList.remove('drag')); zone.addEventListener('drop', (event) => { event.preventDefault(); zone.classList.remove('drag'); showFiles(event.dataTransfer.files); }); }

  async function dashboard() {
    if (!auth || !db) { $('#dashboard-content').innerHTML = '<div class="form-panel"><p class="message">Firebase is not configured. Add the Firebase values in firebase-config.js.</p></div>'; return; }
    auth.onAuthStateChanged(async (user) => {
      if (!user) { window.location.replace('login.html'); return; }
      try { await user.reload(); } catch (error) { setMessage(cleanError(error)); return; }
      const currentUser = auth.currentUser;
      if (!currentUser.emailVerified) { renderVerification(currentUser); return; }
      try { const usernameSnapshot = await db.collection('usernames').where('uid', '==', currentUser.uid).limit(1).get(); if (usernameSnapshot.empty) throw new Error('Your account username record is missing.'); const usernameDoc = usernameSnapshot.docs[0]; const account = usernameDoc.data(); const username = account.username || usernameDoc.id; const profileSnapshot = await db.collection('profiles').doc(username).get(); if (!profileSnapshot.exists) throw new Error('Your profile record is missing.'); if (window.DASHBOARD_EDITOR) return; renderDashboard(username, profileSnapshot.data()); } catch (error) { $('#dashboard-content').innerHTML = `<div class="form-panel"><p class="message">${escapeHtml(cleanError(error))}</p><a class="btn secondary" href="login.html">Return to login</a></div>`; }
    });
  }
  function renderVerification(user) { $('#dashboard-content').innerHTML = `<div class="form-panel"><div class="eyebrow">Email verification</div><h1>One more step</h1><p class="muted">We sent a verification link to ${escapeHtml(user.email)}. Click it, then use the button below.</p><button class="btn" id="resend-dashboard">Send another email</button><button class="btn secondary" id="check-verification">I verified my email</button><p class="message" id="form-message"></p></div>`; $('#resend-dashboard').onclick = async () => { try { await user.sendEmailVerification(); setMessage('A new verification email has been sent.', true); } catch (error) { setMessage(cleanError(error)); } }; $('#check-verification').onclick = async () => { await auth.currentUser.reload(); if (auth.currentUser.emailVerified) location.reload(); else setMessage('Firebase still shows this email as unverified. Click the link in your email first.'); }; }

  function renderDashboard(username, profile) {
    const root = $('#dashboard-content');
    if (profile.activated) { root.innerHTML = `<div class="form-panel"><div class="eyebrow">Welcome back, ${escapeHtml(username)}</div><h1>Your profile is live.</h1><p class="muted">Control whether visitors can see your profile.</p><label class="form-group"><span>Profile visibility</span><input type="checkbox" id="active-toggle" ${profile.active ? 'checked' : ''}> <strong id="status-label">${profile.active ? 'Active' : 'Inactive'}</strong></label><button class="btn secondary" id="logout">Log out</button><p class="message" id="form-message"></p></div>`; $('#active-toggle').onchange = async (event) => { try { await db.collection('profiles').doc(username).update({ active: event.target.checked }); $('#status-label').textContent = event.target.checked ? 'Active' : 'Inactive'; } catch (error) { event.target.checked = !event.target.checked; setMessage(cleanError(error)); } }; $('#logout').onclick = () => auth.signOut().then(() => { location.href = 'index.html'; }); return; }
    root.innerHTML = `<div class="form-panel"><div class="eyebrow">Welcome to imageporn-escorts</div><h1>Complete your profile</h1><p class="muted">Every field below is required before your profile can be published.</p><form id="profile-form"><div class="form-grid"><div class="form-group full"><label>Profile picture</label><div class="dropzone" id="avatar-zone">Click or drag one image here<input id="avatar" type="file" accept="image/*" hidden></div><div class="preview" id="avatar-preview"></div></div><div class="form-group full"><label for="displayName">Display name</label><input id="displayName" required value="${escapeHtml(profile.displayName)}"></div><div class="form-group full"><label for="bio">Bio</label><textarea id="bio" rows="5" minlength="50" required>${escapeHtml(profile.bio)}</textarea><small>At least 50 characters.</small></div><div class="form-group"><label for="country">Country</label><select id="country" required><option value="">Choose country...</option><option>Uganda</option><option>Kenya</option><option>Tanzania</option><option>Rwanda</option><option>South Africa</option><option>United Kingdom</option><option>United States</option></select></div><div class="form-group"><label for="region">Region</label><select id="region" required>${regionOptions(profile.country, profile.region)}</select></div><div class="form-group"><label for="phone">Phone number</label><input id="phone" type="tel" required value="${escapeHtml(profile.phone)}"></div><div class="form-group"><label><input id="whatsapp" type="checkbox" ${profile.whatsapp ? 'checked' : ''}> Available on WhatsApp</label></div><div class="form-group full"><label>Public pictures (minimum 2)</label><div class="dropzone" id="gallery-zone">Click or drag images here<input id="gallery-input" type="file" accept="image/*" multiple hidden></div><div class="preview" id="gallery-preview"></div></div></div><p class="message" id="form-message"></p><button class="btn" type="submit">Publish profile</button></form></div>`;
    const country = $('#country'); const region = $('#region'); country.onchange = () => { region.innerHTML = regionOptions(country.value, ''); };
    setupDropzone($('#avatar-zone'), $('#avatar'), $('#avatar-preview'), false); setupDropzone($('#gallery-zone'), $('#gallery-input'), $('#gallery-preview'), true);
    $('#profile-form').onsubmit = async (event) => { event.preventDefault(); const avatar = $('#avatar')._files?.[0]; const gallery = $('#gallery-input')._files || []; if (!avatar || gallery.length < 2) return setMessage('Add one profile picture and at least two public pictures.'); if ($('#bio').value.trim().length < 50) return setMessage('Your bio must be at least 50 characters.'); try { setMessage('Uploading images...'); const profileImage = await uploadImage(avatar); const publicImages = await Promise.all(gallery.map(uploadImage)); await db.collection('profiles').doc(username).update({ displayName: $('#displayName').value.trim(), bio: $('#bio').value.trim(), country: country.value, region: region.value, phone: $('#phone').value.trim(), whatsapp: $('#whatsapp').checked, profileImage, publicImages, activated: true, active: true, updatedAt: firebase.firestore.FieldValue.serverTimestamp() }); setMessage('Profile published. Welcome aboard.', true); setTimeout(() => location.reload(), 800); } catch (error) { setMessage(cleanError(error)); } };
  }

  async function directory() { const grid = $('#profiles'); if (!grid || !db) return; try { const profiles = []; const snapshot = await db.collection('profiles').where('active', '==', true).get(); snapshot.forEach((doc) => { const data = doc.data(); profiles.push({ id: doc.id, ...data, username: data.username || doc.id }); }); profiles.sort((a, b) => hash(new Date().toISOString().slice(0, 10) + a.id) - hash(new Date().toISOString().slice(0, 10) + b.id)); const render = () => { const term = ($('#search').value || '').trim().toLowerCase(); const gender = $('#gender-filter').value; const visible = profiles.filter((profile) => (!term || `${profile.username} ${profile.bio || ''}`.toLowerCase().includes(term)) && (gender === 'all' || profile.gender === gender)); $('#result-count').textContent = `${visible.length} profile${visible.length === 1 ? '' : 's'}`; grid.innerHTML = visible.length ? visible.map((profile) => `<a class="escort-card" href="imageporn-escort-view.html?user=${encodeURIComponent(profile.username)}" style="background-image:url('${escapeHtml(profile.profileImage || '')}')"><div class="card-info"><span class="tag">${escapeHtml(profile.gender || 'Profile')} · ${escapeHtml(profile.country || 'Location not set')}</span><h3>${escapeHtml(profile.displayName || profile.username)}</h3><p>${escapeHtml(profile.region || 'Region not set')} · ${escapeHtml(profile.age || '18+')} years</p><p>${escapeHtml((profile.bio || 'No bio available.').slice(0, 92))}${(profile.bio || '').length > 92 ? '...' : ''}</p></div></a>`).join('') : '<div class="empty">No active profiles match that search.</div>'; }; $('#search').oninput = render; $('#gender-filter').onchange = render; render(); } catch (error) { grid.innerHTML = `<div class="empty">${escapeHtml(cleanError(error))}</div>`; } }
  async function detail() { const username = new URLSearchParams(location.search).get('user'); const root = $('#detail'); if (!username || !root || !db) return; try { const snapshot = await db.collection('profiles').doc(username).get(); if (!snapshot.exists || !snapshot.data().active) { root.innerHTML = '<div class="empty">This profile is not currently active.</div>'; return; } const profile = snapshot.data(); root.innerHTML = `<div class="detail-top"><img class="profile-photo" src="${escapeHtml(profile.profileImage)}" alt="${escapeHtml(profile.displayName || username)}"><div><div class="eyebrow">Verified profile</div><h1>${escapeHtml(profile.displayName || username)}</h1><div class="facts"><span>${escapeHtml(profile.country)} · ${escapeHtml(profile.region)}</span><span>${escapeHtml(profile.age)} years</span><a href="tel:${escapeHtml(profile.phone)}">${escapeHtml(profile.phone)}</a>${profile.whatsapp ? `<a class="btn" href="https://wa.me/${encodeURIComponent((profile.phone || '').replace(/\D/g, ''))}?text=${encodeURIComponent('Hi 👋, I found your page on imageporn.xyz/escorts')}">WhatsApp</a>` : ''}</div><p class="bio">${escapeHtml(profile.bio)}</p></div></div><div class="gallery">${(profile.publicImages || []).map((url) => `<img src="${escapeHtml(url)}" alt="Public profile image" loading="lazy">`).join('')}</div><div class="muted">Page visits: <strong id="visits">...</strong></div>`; const visitKey = `visited-${username}`; let visits = Number(profile.visits || 0); if (!localStorage.getItem(visitKey)) { localStorage.setItem(visitKey, 'yes'); visits += 1; await db.collection('profiles').doc(username).update({ visits }); } $('#visits').textContent = visits; } catch (error) { root.innerHTML = `<div class="empty">${escapeHtml(cleanError(error))}</div>`; } }
  if (page === 'directory') directory(); if (page === 'auth') authPage(); if (page === 'dashboard' && document.body.dataset.dashboardEditor !== 'true') dashboard(); if (page === 'detail') detail();
})();
